# Generated by DaoMake: DO NOT EDIT!
# Targeting platform macosx.

all: libdao_graphics.dylib libdao_graphics.a

.PHONY: test
test: libdao_graphics.dylib libdao_graphics.a subtest 


DAOMAKE = /Users/min/Projects/dao/tools/daomake/bootstrap/daomake


HEADERS_18E8 = source/dao_common.h source/dao_font.h source/dao_image.h source/dao_path.h source/dao_canvas.h source/dao_mesh.h source/dao_scene.h source/dao_triangulator.h source/dao_painter.h source/dao_renderer.h source/dao_resource.h source/dao_xml.h source/dao_collada.h source/dao_opengl.h source/dao_glut.h

CFLAGS_719E =-ggdb -O0 -DDEBUG -fPIC -I../../kernel/ -DDAO_WITH_MACRO -DDAO_WITH_REGEX -DDAO_WITH_LONGINT -DDAO_WITH_NUMARRAY -DDAO_WITH_DYNCLASS -DDAO_WITH_DECORATOR -DDAO_WITH_THREAD -DDAO_WITH_CONCURRENT -DUNIX -DMAC_OSX -I/System/Library/Frameworks/OpenGL.framework/Headers -I/System/Library/Frameworks/GLUT.framework/Headers 


LFLAGS_3431 =-ggdb -lm -lpthread -framework OpenGL -framework GLUT -dynamiclib -install_name @rpath/libdao_graphics.dylib -undefined dynamic_lookup


DaoMake.Objs/dao_canvas.c.0BDA.o: source/dao_canvas.c $(HEADERS_18E8)
	$(CC) $(CFLAGS_719E) -c source/dao_canvas.c -o DaoMake.Objs/dao_canvas.c.0BDA.o

DaoMake.Objs/dao_collada.c.CE0C.o: source/dao_collada.c $(HEADERS_18E8)
	$(CC) $(CFLAGS_719E) -c source/dao_collada.c -o DaoMake.Objs/dao_collada.c.CE0C.o

DaoMake.Objs/dao_common.c.E8AE.o: source/dao_common.c $(HEADERS_18E8)
	$(CC) $(CFLAGS_719E) -c source/dao_common.c -o DaoMake.Objs/dao_common.c.E8AE.o

DaoMake.Objs/dao_font.c.BE4D.o: source/dao_font.c $(HEADERS_18E8)
	$(CC) $(CFLAGS_719E) -c source/dao_font.c -o DaoMake.Objs/dao_font.c.BE4D.o

DaoMake.Objs/dao_glut.c.7B00.o: source/dao_glut.c $(HEADERS_18E8)
	$(CC) $(CFLAGS_719E) -c source/dao_glut.c -o DaoMake.Objs/dao_glut.c.7B00.o

DaoMake.Objs/dao_graphics.c.8ED1.o: source/dao_graphics.c $(HEADERS_18E8)
	$(CC) $(CFLAGS_719E) -c source/dao_graphics.c -o DaoMake.Objs/dao_graphics.c.8ED1.o

DaoMake.Objs/dao_image.c.92EA.o: source/dao_image.c $(HEADERS_18E8)
	$(CC) $(CFLAGS_719E) -c source/dao_image.c -o DaoMake.Objs/dao_image.c.92EA.o

DaoMake.Objs/dao_mesh.c.72F8.o: source/dao_mesh.c $(HEADERS_18E8)
	$(CC) $(CFLAGS_719E) -c source/dao_mesh.c -o DaoMake.Objs/dao_mesh.c.72F8.o

DaoMake.Objs/dao_opengl.c.3395.o: source/dao_opengl.c $(HEADERS_18E8)
	$(CC) $(CFLAGS_719E) -c source/dao_opengl.c -o DaoMake.Objs/dao_opengl.c.3395.o

DaoMake.Objs/dao_painter.c.BC9D.o: source/dao_painter.c $(HEADERS_18E8)
	$(CC) $(CFLAGS_719E) -c source/dao_painter.c -o DaoMake.Objs/dao_painter.c.BC9D.o

DaoMake.Objs/dao_path.c.CF29.o: source/dao_path.c $(HEADERS_18E8)
	$(CC) $(CFLAGS_719E) -c source/dao_path.c -o DaoMake.Objs/dao_path.c.CF29.o

DaoMake.Objs/dao_renderer.c.5E42.o: source/dao_renderer.c $(HEADERS_18E8)
	$(CC) $(CFLAGS_719E) -c source/dao_renderer.c -o DaoMake.Objs/dao_renderer.c.5E42.o

DaoMake.Objs/dao_resource.c.509B.o: source/dao_resource.c $(HEADERS_18E8)
	$(CC) $(CFLAGS_719E) -c source/dao_resource.c -o DaoMake.Objs/dao_resource.c.509B.o

DaoMake.Objs/dao_scene.c.DFED.o: source/dao_scene.c $(HEADERS_18E8)
	$(CC) $(CFLAGS_719E) -c source/dao_scene.c -o DaoMake.Objs/dao_scene.c.DFED.o

DaoMake.Objs/dao_triangulator.c.84B9.o: source/dao_triangulator.c $(HEADERS_18E8)
	$(CC) $(CFLAGS_719E) -c source/dao_triangulator.c -o DaoMake.Objs/dao_triangulator.c.84B9.o

DaoMake.Objs/dao_xml.c.13F7.o: source/dao_xml.c $(HEADERS_18E8)
	$(CC) $(CFLAGS_719E) -c source/dao_xml.c -o DaoMake.Objs/dao_xml.c.13F7.o


OBJECTS_09CA =DaoMake.Objs/dao_common.c.E8AE.o DaoMake.Objs/dao_font.c.BE4D.o DaoMake.Objs/dao_image.c.92EA.o DaoMake.Objs/dao_path.c.CF29.o DaoMake.Objs/dao_canvas.c.0BDA.o DaoMake.Objs/dao_mesh.c.72F8.o DaoMake.Objs/dao_scene.c.DFED.o DaoMake.Objs/dao_triangulator.c.84B9.o DaoMake.Objs/dao_painter.c.BC9D.o DaoMake.Objs/dao_renderer.c.5E42.o DaoMake.Objs/dao_graphics.c.8ED1.o DaoMake.Objs/dao_resource.c.509B.o DaoMake.Objs/dao_xml.c.13F7.o DaoMake.Objs/dao_collada.c.CE0C.o DaoMake.Objs/dao_opengl.c.3395.o DaoMake.Objs/dao_glut.c.7B00.o


libdao_graphics.dylib: $(OBJECTS_09CA)
	$(CC) $(OBJECTS_09CA) $(LFLAGS_3431)  -o libdao_graphics.dylib

libdao_graphics.a: $(OBJECTS_09CA)
	-@$(DAOMAKE) remove libdao_graphics.a
	ar rcs libdao_graphics.a $(OBJECTS_09CA)

subtest:

.PHONY: subtest

TESTSUM =/Users/min/Projects/dao/daotest_result_summary.txt

testsum:

.PHONY: testsum

install:
	$(DAOMAKE) mkdir2 /usr/local/lib/dao
	$(DAOMAKE) mkdir2 /usr/local/lib/dao/modules
	$(DAOMAKE) copy libdao_graphics.dylib /usr/local/lib/dao/modules
	$(DAOMAKE) copy libdao_graphics.a /usr/local/lib/dao/modules


uninstall:
	$(DAOMAKE) remove /usr/local/lib/dao
	$(DAOMAKE) remove /usr/local/lib/dao/modules


.PHONY: install uninstall

clean:
	$(DAOMAKE) remove $(OBJECTS_09CA)

.PHONY: clean

